apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: dev
  labels:
    app: node-api
spec:
  selector:
    matchLabels:
      app: node-api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: node-api
          image: ghcr.io/champalab/node-api:e67267d9e8f6a5cc8aab77103218a0261e9c8737
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          
          envFrom:
            - configMapRef:
                name: node-api-config
          ports:
            - containerPort: 3000
              name: node-api
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: vol-dummy
              mountPath: /app/uploads
              subPath: node-api/uploads
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Bangkok
        - name: vol-dummy

      restartPolicy: Always
