apiVersion: v1
kind: Service
metadata:
  name: node-api
  namespace: dev
spec:
  selector:
    app: node-api
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: node-api-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000